-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 10:19:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rimoldi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rimoldi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rimoldi` DEFAULT CHARACTER SET utf8 ;
USE `rimoldi` ;

-- -----------------------------------------------------
-- Table `rimoldi`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Persona` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` INT NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `cuil` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Inquilino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Inquilino` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Inquilino` (
  `mascotas` TINYINT NOT NULL,
  `empresa_trabaja` VARCHAR(45) NOT NULL,
  `cantidad_integrantes` VARCHAR(45) NOT NULL,
  `ingresos` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  `idInquilino` INT NOT NULL,
  PRIMARY KEY (`Persona_id`, `idInquilino`),
  CONSTRAINT `fk_Inquilino_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Garante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Garante` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Garante` (
  `ingresos` INT NOT NULL,
  `empresa_trabaja` VARCHAR(45) NOT NULL,
  `contacto_trabaja` VARCHAR(45) NOT NULL,
  `Persona_id` INT NOT NULL,
  `idGarante` INT NOT NULL,
  PRIMARY KEY (`Persona_id`, `idGarante`),
  INDEX `fk_Garante_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Garante_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Propietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Propietario` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Propietario` (
  `cbu` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  `idPropietario` INT NOT NULL,
  PRIMARY KEY (`Persona_id`, `idPropietario`),
  INDEX `fk_Propietario_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Propietario_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Propiedad` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Propiedad` (
  `idPropiedad` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `alquiler` DOUBLE NOT NULL,
  `m2_cubiertos` INT NULL,
  `m2_descubiertos` INT NULL,
  `condiciones_garantes` VARCHAR(45) NOT NULL,
  `expensas` DOUBLE NULL,
  `gastos` DOUBLE NULL,
  `fecha_precio_minimo` DATE NOT NULL,
  `Propietario_Persona_id` INT NOT NULL,
  `cuidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPropiedad`),
  INDEX `fk_Propiedad_Propietario1_idx` (`Propietario_Persona_id` ASC) VISIBLE,
  UNIQUE INDEX `idPropiedad_UNIQUE` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `fk_Propiedad_Propietario1`
    FOREIGN KEY (`Propietario_Persona_id`)
    REFERENCES `rimoldi`.`Propietario` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Martillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Martillero` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Martillero` (
  `idMartillero` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nro_matricula` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`idMartillero`, `Persona_id`),
  INDEX `fk_Martillero_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Martillero_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Contrato` (
  `nro_contrato` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_cancelacion` DATE NULL,
  `Propiedad_idPropiedad` INT NOT NULL,
  `Inquilino_Persona_id` INT NOT NULL,
  `Martillero_idMartillero` INT NOT NULL,
  `Martillero_Persona_id` INT NOT NULL,
  PRIMARY KEY (`nro_contrato`),
  INDEX `fk_Contrato_Propiedad1_idx` (`Propiedad_idPropiedad` ASC) VISIBLE,
  INDEX `fk_Contrato_Inquilino1_idx` (`Inquilino_Persona_id` ASC) VISIBLE,
  INDEX `fk_Contrato_Martillero1_idx` (`Martillero_idMartillero` ASC, `Martillero_Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Propiedad1`
    FOREIGN KEY (`Propiedad_idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Inquilino1`
    FOREIGN KEY (`Inquilino_Persona_id`)
    REFERENCES `rimoldi`.`Inquilino` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Contrato_Martillero1
    FOREIGN KEY (Martillero_Persona_id)
    REFERENCES `rimoldi`.`Martillero` (Persona_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Familiar` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Familiar` (
  `cant_ambientes` INT NOT NULL,
  `cant_baños` INT NOT NULL,
  `cant_autos_cochera` INT NOT NULL,
  `piscina` TINYINT NOT NULL,
  `permite_mascotas` TINYINT NOT NULL,
  `permite_niños` TINYINT NOT NULL,
  `Propiedad_idPropiedad` INT NOT NULL,
  `idFamiliar` INT NOT NULL,
  PRIMARY KEY (`Propiedad_idPropiedad`, `idFamiliar`),
  CONSTRAINT `fk_Familiar_Propiedad1`
    FOREIGN KEY (`Propiedad_idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Comercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Comercial` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Comercial` (
  `permisos_municipales` VARCHAR(45) NOT NULL,
  `baño` TINYINT NOT NULL,
  `cocina` TINYINT NOT NULL,
  `vidriera` TINYINT NOT NULL,
  `deposito` TINYINT NOT NULL,
  `Propiedad_idPropiedad` INT NOT NULL,
  `idComercial` INT NOT NULL,
  PRIMARY KEY (`Propiedad_idPropiedad`, `idComercial`),
  CONSTRAINT `fk_Comercial_Propiedad1`
    FOREIGN KEY (`Propiedad_idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Firma` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Firma` (
  `Contrato_nro_contrato` INT NOT NULL,
  `Garante_Persona_id` INT NOT NULL,
  PRIMARY KEY (`Contrato_nro_contrato`, `Garante_Persona_id`),
  INDEX `fk_Contrato_has_Garante_Garante1_idx` (`Garante_Persona_id` ASC) VISIBLE,
  INDEX `fk_Contrato_has_Garante_Contrato1_idx` (`Contrato_nro_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_has_Garante_Contrato1`
    FOREIGN KEY (`Contrato_nro_contrato`)
    REFERENCES `rimoldi`.`Contrato` (`nro_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Garante_Garante1`
    FOREIGN KEY (`Garante_Persona_id`)
    REFERENCES `rimoldi`.`Garante` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Estado` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Estado` (
  `idEstado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`EstadoContrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`EstadoContrato` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`EstadoContrato` (
  `Contrato_nro_contrato` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`Contrato_nro_contrato`, `Estado_idEstado`),
  INDEX `fk_Contrato_has_Estado_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  INDEX `fk_Contrato_has_Estado_Contrato1_idx` (`Contrato_nro_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_has_Estado_Contrato1`
    FOREIGN KEY (`Contrato_nro_contrato`)
    REFERENCES `rimoldi`.`Contrato` (`nro_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Estado_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `rimoldi`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
