-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 16:06:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rimoldi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rimoldi` ;

-- -----------------------------------------------------
-- Schema rimoldi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rimoldi` DEFAULT CHARACTER SET utf8 ;
USE `rimoldi` ;

-- -----------------------------------------------------
-- Table `rimoldi`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Persona` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` BIGINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` BIGINT NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `cuil` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Inquilino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Inquilino` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Inquilino` (
  `idInquilino` INT NOT NULL,
  `mascotas` TINYINT NOT NULL,
  `empresa_trabaja` VARCHAR(45) NOT NULL,
  `cantidad_integrantes` VARCHAR(45) NOT NULL,
  `ingresos` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idInquilino`, `idPersona`),
  CONSTRAINT `fk_Inquilino_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Garante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Garante` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Garante` (
  `idGarante` INT NOT NULL,
  `ingresos` INT NOT NULL,
  `empresa_trabaja` VARCHAR(45) NOT NULL,
  `contacto_trabaja` VARCHAR(45) NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idGarante`, `idPersona`),
  INDEX `fk_Garante_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Garante_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Propietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Propietario` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Propietario` (
  `idPropietario` INT NOT NULL,
  `cbu` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idPropietario`, `idPersona`),
  INDEX `fk_Propietario_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Propietario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Propiedad` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Propiedad` (
  `idPropiedad` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `alquiler` DOUBLE NOT NULL,
  `m2_cubiertos` INT NOT NULL,
  `m2_descubiertos` INT NOT NULL,
  `condiciones_garantes` VARCHAR(45) NOT NULL,
  `expensas` DOUBLE NOT NULL,
  `gastos` DOUBLE NOT NULL,
  `fecha_precio_minimo` DATE NOT NULL,
  `cuidad` VARCHAR(45) NOT NULL,
  `idPropietario` INT NOT NULL,
  PRIMARY KEY (`idPropiedad`),
  INDEX `fk_Propiedad_Propietario1_idx` (`idPropietario` ASC) VISIBLE,
  UNIQUE INDEX `idPropiedad_UNIQUE` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `fk_Propiedad_Propietario1`
    FOREIGN KEY (`idPropietario`)
    REFERENCES `rimoldi`.`Propietario` (`idPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Martillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Martillero` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Martillero` (
  `idMartillero` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nro_matricula` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idMartillero`, `idPersona`),
  INDEX `fk_Martillero_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Martillero_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `rimoldi`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Contrato` (
  `nro_contrato` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_cancelacion` DATE NULL,
  `idPropiedad` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `idMartillero` INT NOT NULL,
  PRIMARY KEY (`nro_contrato`),
  INDEX `fk_Contrato_Propiedad1_idx` (`idPropiedad` ASC) VISIBLE,
  INDEX `fk_Contrato_Inquilino1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Contrato_Martillero1_idx` (`idMartillero` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Propiedad1`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Inquilino1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `rimoldi`.`Inquilino` (`idInquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Martillero1`
    FOREIGN KEY (`idMartillero`)
    REFERENCES `rimoldi`.`Martillero` (`idMartillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Familiar` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Familiar` (
  `idFamiliar` INT NOT NULL,
  `cant_ambientes` INT NOT NULL,
  `cant_baños` INT NOT NULL,
  `cant_autos_cochera` INT NOT NULL,
  `piscina` TINYINT NOT NULL,
  `permite_mascotas` TINYINT NOT NULL,
  `permite_niños` TINYINT NOT NULL,
  `idPropiedad` INT NOT NULL,
  PRIMARY KEY (`idFamiliar`, `idPropiedad`),
  CONSTRAINT `fk_Familiar_Propiedad1`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Comercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Comercial` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Comercial` (
  `idComercial` INT NOT NULL,
  `permisos_municipales` VARCHAR(45) NOT NULL,
  `baño` TINYINT NOT NULL,
  `cocina` TINYINT NOT NULL,
  `vidriera` TINYINT NOT NULL,
  `deposito` TINYINT NOT NULL,
  `idPropiedad` INT NOT NULL,
  PRIMARY KEY (`idComercial`, `idPropiedad`),
  CONSTRAINT `fk_Comercial_Propiedad1`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `rimoldi`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Firma` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Firma` (
  `nro_contrato` INT NOT NULL,
  `idGarante` INT NOT NULL,
  PRIMARY KEY (`nro_contrato`, `idGarante`),
  INDEX `fk_Contrato_has_Garante_Garante1_idx` (`idGarante` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_has_Garante_Contrato1`
    FOREIGN KEY (`nro_contrato`)
    REFERENCES `rimoldi`.`Contrato` (`nro_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Garante_Garante1`
    FOREIGN KEY (`idGarante`)
    REFERENCES `rimoldi`.`Garante` (`idGarante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`Estado` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`Estado` (
  `idEstado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rimoldi`.`EstadoContrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rimoldi`.`EstadoContrato` ;

CREATE TABLE IF NOT EXISTS `rimoldi`.`EstadoContrato` (
  `nro_contrato` INT NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`nro_contrato`, `idEstado`),
  INDEX `fk_Contrato_has_Estado_Estado1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_Contrato_has_Estado_Contrato1_idx` (`nro_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_has_Estado_Contrato1`
    FOREIGN KEY (`nro_contrato`)
    REFERENCES `rimoldi`.`Contrato` (`nro_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_has_Estado_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `rimoldi`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
