import "../app/globals.css";

export const metadata = {
  title: "Rimoldi Inmobiliaria",
  description: "Generated by Balta & Laure",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

